// prayers.ts — Prayer Wall data layer. One job: persist and read prayer
// requests via Deno KV. Pure, explicit functions — no HTML, no HTTP.

import { PRAYER_CATEGORIES } from "./content.ts";
import { kv } from "./kv.ts";

const PRAYERS = "prayers";
const LEGACY_SAMPLE_CLEANUP = ["migrations", "remove_sample_prayers_v1"] as const;

// These exact records were generated by the app before the Prayer Wall went live.
// Matching both name and body prevents the migration from touching genuine requests.
const LEGACY_SAMPLES = new Set([
  "Grace O.\nPlease pray for my mother's surgery this Friday — for steady hands for the surgeons and peace over our whole family.",
  "\nBelieving God for a new job after a long season of waiting. Standing on Philippians 4:19.",
  "Daniel\nPray for my younger brother to encounter Jesus. He feels far from God right now, but I know nothing is too hard for the Lord.",
  "Ruth M.\nPraying for peace and steady faith as I wait on biopsy results this week.",
]);

export type PrayerStatus = "active" | "answered";

export interface Prayer {
  id: string;
  name: string; // empty string => shown as "Anonymous"
  body: string;
  category: string;
  status: PrayerStatus;
  prayedCount: number;
  createdAt: number;
  answeredAt: number | null;
  outcome: string | null; // the praise report recorded when answered
}

export interface PrayerStats {
  requests: number;
  prayersOffered: number;
  answered: number;
}

export interface NewPrayer {
  name: string;
  body: string;
  category: string;
}

/** Create a new active prayer request. Returns the stored record. */
export async function addPrayer(input: NewPrayer): Promise<Prayer> {
  const category = (PRAYER_CATEGORIES as readonly string[]).includes(input.category)
    ? input.category
    : "Other";
  const prayer: Prayer = {
    id: crypto.randomUUID(),
    name: input.name.trim().slice(0, 60),
    body: input.body.trim().slice(0, 600),
    category,
    status: "active",
    prayedCount: 0,
    createdAt: Date.now(),
    answeredAt: null,
    outcome: null,
  };
  await kv.set([PRAYERS, prayer.id], prayer);
  return prayer;
}

/** List requests with the given status, newest first. */
export async function listPrayers(status: PrayerStatus): Promise<Prayer[]> {
  const out: Prayer[] = [];
  for await (const entry of kv.list<Prayer>({ prefix: [PRAYERS] })) {
    if (entry.value.status === status) out.push(entry.value);
  }
  const time = (p: Prayer) => status === "answered" ? (p.answeredAt ?? 0) : p.createdAt;
  out.sort((a, b) => time(b) - time(a));
  return out;
}

/**
 * Record one more "I prayed for this". Returns the new count, or null if the
 * request no longer exists. Uses an atomic check so concurrent taps don't race.
 */
export async function prayFor(id: string): Promise<number | null> {
  for (let attempt = 0; attempt < 8; attempt++) {
    const entry = await kv.get<Prayer>([PRAYERS, id]);
    if (!entry.value) return null;
    const updated: Prayer = {
      ...entry.value,
      prayedCount: entry.value.prayedCount + 1,
    };
    const res = await kv.atomic().check(entry).set([PRAYERS, id], updated).commit();
    if (res.ok) return updated.prayedCount;
  }
  return null; // gave up under contention
}

/**
 * Move a request into the answered (testimony) list, optionally recording the
 * praise report describing what God did.
 */
export async function markAnswered(id: string, outcome = ""): Promise<boolean> {
  const entry = await kv.get<Prayer>([PRAYERS, id]);
  if (!entry.value || entry.value.status === "answered") return false;
  const updated: Prayer = {
    ...entry.value,
    status: "answered",
    answeredAt: Date.now(),
    outcome: outcome.trim().slice(0, 600) || null,
  };
  const res = await kv.atomic().check(entry).set([PRAYERS, id], updated).commit();
  return res.ok;
}

/** Permanently remove a request or answered testimony. */
export async function deletePrayer(id: string): Promise<boolean> {
  if (!id) return false;
  const entry = await kv.get<Prayer>([PRAYERS, id]);
  if (!entry.value) return false;
  const res = await kv.atomic().check(entry).delete([PRAYERS, id]).commit();
  return res.ok;
}

/**
 * Remove the four fictional records shipped by older releases. This migration
 * runs once and matches their exact name/body pairs, leaving real submissions intact.
 */
export async function removeLegacySamplePrayers(): Promise<void> {
  const migrated = await kv.get(LEGACY_SAMPLE_CLEANUP);
  if (migrated.value) return;

  for await (const entry of kv.list<Prayer>({ prefix: [PRAYERS] })) {
    if (LEGACY_SAMPLES.has(`${entry.value.name}\n${entry.value.body}`)) {
      await kv.delete(entry.key);
    }
  }

  await kv.set(LEGACY_SAMPLE_CLEANUP, true);
  await kv.delete(["prayers_seeded"]);
}

/** Aggregate counts for the headline stats row. */
export async function getStats(): Promise<PrayerStats> {
  const stats: PrayerStats = { requests: 0, prayersOffered: 0, answered: 0 };
  for await (const entry of kv.list<Prayer>({ prefix: [PRAYERS] })) {
    stats.requests++;
    stats.prayersOffered += entry.value.prayedCount;
    if (entry.value.status === "answered") stats.answered++;
  }
  return stats;
}
